<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-01NK0AV" ignored="0" name="test1" tests="5" failures="2" timestamp="2020-11-12T11:33:39 CST" time="55.546" errors="0">
  <testcase name="test1" time="0.007" classname="com.jianyu.testcases.TestLoginPage">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at com.jianyu.testcases.TestLoginPage.test1(TestLoginPage.java:46)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.001" classname="com.jianyu.testcases.TestLoginPage"/>
  <testcase name="test3" time="0.0" classname="com.jianyu.testcases.TestLoginPage">
    <failure type="java.lang.AssertionError" message="expected [3] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [1]
at com.jianyu.testcases.TestLoginPage.test3(TestLoginPage.java:54)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="login_fail" time="20.161" classname="com.jianyu.testcases.TestLoginPage"/>
  <testcase name="login_success" time="10.482" classname="com.jianyu.testcases.TestLoginPage"/>
</testsuite> <!-- test1 -->
